//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluxionViewer.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FluxionViewer.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About_Visit {
            get {
                return ResourceManager.GetString("About_Visit", resourceCulture);
            }
        }
        
        public static string About_About {
            get {
                return ResourceManager.GetString("About_About", resourceCulture);
            }
        }
        
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        public static string About_TechUsed {
            get {
                return ResourceManager.GetString("About_TechUsed", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string About_AboutDesc {
            get {
                return ResourceManager.GetString("About_AboutDesc", resourceCulture);
            }
        }
        
        public static string help_0 {
            get {
                return ResourceManager.GetString("help_0", resourceCulture);
            }
        }
        
        public static string help_1 {
            get {
                return ResourceManager.GetString("help_1", resourceCulture);
            }
        }
        
        public static string help_2 {
            get {
                return ResourceManager.GetString("help_2", resourceCulture);
            }
        }
        
        public static string help_3 {
            get {
                return ResourceManager.GetString("help_3", resourceCulture);
            }
        }
        
        public static string help_4 {
            get {
                return ResourceManager.GetString("help_4", resourceCulture);
            }
        }
        
        public static string help_5 {
            get {
                return ResourceManager.GetString("help_5", resourceCulture);
            }
        }
        
        public static string cli_notenoughargs {
            get {
                return ResourceManager.GetString("cli_notenoughargs", resourceCulture);
            }
        }
        
        public static string help_6 {
            get {
                return ResourceManager.GetString("help_6", resourceCulture);
            }
        }
        
        public static string help_7 {
            get {
                return ResourceManager.GetString("help_7", resourceCulture);
            }
        }
        
        public static string help_8 {
            get {
                return ResourceManager.GetString("help_8", resourceCulture);
            }
        }
        
        public static string cli_unsupportedcompression {
            get {
                return ResourceManager.GetString("cli_unsupportedcompression", resourceCulture);
            }
        }
        
        public static string cli_unsupportedencoding {
            get {
                return ResourceManager.GetString("cli_unsupportedencoding", resourceCulture);
            }
        }
        
        public static string FileExtName {
            get {
                return ResourceManager.GetString("FileExtName", resourceCulture);
            }
        }
        
        public static string Status_LoadingFile {
            get {
                return ResourceManager.GetString("Status_LoadingFile", resourceCulture);
            }
        }
        
        public static string Status_SavingFile {
            get {
                return ResourceManager.GetString("Status_SavingFile", resourceCulture);
            }
        }
        
        public static string Attribute_Remove {
            get {
                return ResourceManager.GetString("Attribute_Remove", resourceCulture);
            }
        }
        
        public static string ValueType_Null {
            get {
                return ResourceManager.GetString("ValueType_Null", resourceCulture);
            }
        }
        
        public static string ValueType_True {
            get {
                return ResourceManager.GetString("ValueType_True", resourceCulture);
            }
        }
        
        public static string ValueType_False {
            get {
                return ResourceManager.GetString("ValueType_False", resourceCulture);
            }
        }
        
        public static string ValueType_Char {
            get {
                return ResourceManager.GetString("ValueType_Char", resourceCulture);
            }
        }
        
        public static string ValueType_Short {
            get {
                return ResourceManager.GetString("ValueType_Short", resourceCulture);
            }
        }
        
        public static string ValueType_UShort {
            get {
                return ResourceManager.GetString("ValueType_UShort", resourceCulture);
            }
        }
        
        public static string ValueType_Byte {
            get {
                return ResourceManager.GetString("ValueType_Byte", resourceCulture);
            }
        }
        
        public static string ValueType_SByte {
            get {
                return ResourceManager.GetString("ValueType_SByte", resourceCulture);
            }
        }
        
        public static string ValueType_Int {
            get {
                return ResourceManager.GetString("ValueType_Int", resourceCulture);
            }
        }
        
        public static string ValueType_UInt {
            get {
                return ResourceManager.GetString("ValueType_UInt", resourceCulture);
            }
        }
        
        public static string ValueType_Long {
            get {
                return ResourceManager.GetString("ValueType_Long", resourceCulture);
            }
        }
        
        public static string ValueType_ULong {
            get {
                return ResourceManager.GetString("ValueType_ULong", resourceCulture);
            }
        }
        
        public static string ValueType_Float {
            get {
                return ResourceManager.GetString("ValueType_Float", resourceCulture);
            }
        }
        
        public static string ValueType_Double {
            get {
                return ResourceManager.GetString("ValueType_Double", resourceCulture);
            }
        }
        
        public static string ValueType_String {
            get {
                return ResourceManager.GetString("ValueType_String", resourceCulture);
            }
        }
        
        public static string ValueType_ByteArray {
            get {
                return ResourceManager.GetString("ValueType_ByteArray", resourceCulture);
            }
        }
        
        public static string Node_NewItem {
            get {
                return ResourceManager.GetString("Node_NewItem", resourceCulture);
            }
        }
        
        public static string Node_Root {
            get {
                return ResourceManager.GetString("Node_Root", resourceCulture);
            }
        }
        
        public static string Node_NewAttr {
            get {
                return ResourceManager.GetString("Node_NewAttr", resourceCulture);
            }
        }
        
        public static string Attr_Name {
            get {
                return ResourceManager.GetString("Attr_Name", resourceCulture);
            }
        }
        
        public static string Attr_Value {
            get {
                return ResourceManager.GetString("Attr_Value", resourceCulture);
            }
        }
        
        public static string Open_Title {
            get {
                return ResourceManager.GetString("Open_Title", resourceCulture);
            }
        }
        
        public static string OpenCompressed_Title {
            get {
                return ResourceManager.GetString("OpenCompressed_Title", resourceCulture);
            }
        }
        
        public static string SaveAs_Title {
            get {
                return ResourceManager.GetString("SaveAs_Title", resourceCulture);
            }
        }
        
        public static string SaveConfirmDialog {
            get {
                return ResourceManager.GetString("SaveConfirmDialog", resourceCulture);
            }
        }
        
        public static string SaveConfirmYes {
            get {
                return ResourceManager.GetString("SaveConfirmYes", resourceCulture);
            }
        }
        
        public static string SaveConfirmNo {
            get {
                return ResourceManager.GetString("SaveConfirmNo", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Tab_Attr {
            get {
                return ResourceManager.GetString("Tab_Attr", resourceCulture);
            }
        }
        
        public static string Attr_Type {
            get {
                return ResourceManager.GetString("Attr_Type", resourceCulture);
            }
        }
        
        public static string Tab_Prop {
            get {
                return ResourceManager.GetString("Tab_Prop", resourceCulture);
            }
        }
        
        public static string Splitter_Tooltip {
            get {
                return ResourceManager.GetString("Splitter_Tooltip", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string Setting_AutoSave {
            get {
                return ResourceManager.GetString("Setting_AutoSave", resourceCulture);
            }
        }
        
        public static string ToolTip_About {
            get {
                return ResourceManager.GetString("ToolTip_About", resourceCulture);
            }
        }
        
        public static string ToolTip_Paste {
            get {
                return ResourceManager.GetString("ToolTip_Paste", resourceCulture);
            }
        }
        
        public static string ToolTip_Cut {
            get {
                return ResourceManager.GetString("ToolTip_Cut", resourceCulture);
            }
        }
        
        public static string ToolTip_Copy {
            get {
                return ResourceManager.GetString("ToolTip_Copy", resourceCulture);
            }
        }
        
        public static string ToolTip_Add {
            get {
                return ResourceManager.GetString("ToolTip_Add", resourceCulture);
            }
        }
        
        public static string ToolTip_Delete {
            get {
                return ResourceManager.GetString("ToolTip_Delete", resourceCulture);
            }
        }
        
        public static string ToolTip_Open {
            get {
                return ResourceManager.GetString("ToolTip_Open", resourceCulture);
            }
        }
        
        public static string ToolTip_OpenCompressed {
            get {
                return ResourceManager.GetString("ToolTip_OpenCompressed", resourceCulture);
            }
        }
        
        public static string ToolTip_Compression {
            get {
                return ResourceManager.GetString("ToolTip_Compression", resourceCulture);
            }
        }
        
        public static string ToolTipButton_Load {
            get {
                return ResourceManager.GetString("ToolTipButton_Load", resourceCulture);
            }
        }
        
        public static string ToolTip_Encoding {
            get {
                return ResourceManager.GetString("ToolTip_Encoding", resourceCulture);
            }
        }
        
        public static string ToolTipButton_Save {
            get {
                return ResourceManager.GetString("ToolTipButton_Save", resourceCulture);
            }
        }
        
        public static string ToolTip_SaveFile {
            get {
                return ResourceManager.GetString("ToolTip_SaveFile", resourceCulture);
            }
        }
        
        public static string ToolTip_SaveFileAs {
            get {
                return ResourceManager.GetString("ToolTip_SaveFileAs", resourceCulture);
            }
        }
        
        public static string Compression_None {
            get {
                return ResourceManager.GetString("Compression_None", resourceCulture);
            }
        }
        
        public static string ToolTip_Settings {
            get {
                return ResourceManager.GetString("ToolTip_Settings", resourceCulture);
            }
        }
        
        public static string Attr_Add {
            get {
                return ResourceManager.GetString("Attr_Add", resourceCulture);
            }
        }
        
        public static string FluxionVersionSelect {
            get {
                return ResourceManager.GetString("FluxionVersionSelect", resourceCulture);
            }
        }
        
        public static string Update_CheckForUpdates {
            get {
                return ResourceManager.GetString("Update_CheckForUpdates", resourceCulture);
            }
        }
        
        public static string Update_UpdateAvailable {
            get {
                return ResourceManager.GetString("Update_UpdateAvailable", resourceCulture);
            }
        }
        
        public static string Update_UpToDate {
            get {
                return ResourceManager.GetString("Update_UpToDate", resourceCulture);
            }
        }
        
        public static string Update_1 {
            get {
                return ResourceManager.GetString("Update_1", resourceCulture);
            }
        }
        
        public static string Update_2 {
            get {
                return ResourceManager.GetString("Update_2", resourceCulture);
            }
        }
        
        public static string Update_3 {
            get {
                return ResourceManager.GetString("Update_3", resourceCulture);
            }
        }
        
        public static string Update_4 {
            get {
                return ResourceManager.GetString("Update_4", resourceCulture);
            }
        }
    }
}
