name: FluxionViewer iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
            with:
                xcode-version: latest-stable
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup workloads
        run: dotnet workload restore ./src/FluxionViewer.sln
      - name: Restore dependencies
        run: dotnet restore ./src/FluxionViewer.iOS/FluxionViewer.iOS.csproj
      - name: Build
        run: dotnet build --no-restore ./src/FluxionViewer.iOS/FluxionViewer.iOS.csproj
      - name: Publish (iOS)
        run: dotnet publish --no-restore ./src/FluxionViewer.iOS/FluxionViewer.iOS.csproj -c Release -f net8.0-ios -o ./publish/ios -r ios-arm64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FluxionViewer iOS
          path: ./publish/ios/
