# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: FluxionViewer macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup workloads
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore ./src/FluxionViewer.macOS/FluxionViewer.macOS.csproj
      - name: Build
        run: dotnet build --no-restore ./src/FluxionViewer.macOS/FluxionViewer.macOS.csproj
      
      # macOS Intel
      - name: Publish (macOS Intel)
        run: |
          dotnet publish -c Release -r osx-x64 -o ./publish/osx-x64/ ./src/FluxionViewer.macOS/FluxionViewer.macOS.csproj
          rm ./publish/osx-x64/*.dbg
      - name: Upload Artifact (macOS Intel)
        uses: actions/upload-artifact@v4
        with:
          name: FluxionViewer macOS Intel
          path: ./publish/osx-x64/
      
      # macOS ARM
      - name: Publish (macOS ARM)
        run: |
          dotnet publish -c Release -r osx-arm64 -o ./publish/osx-arm64/ ./src/FluxionViewer.macOS/FluxionViewer.macOS.csproj
          rm ./publish/osx-arm64/*.dbg
      - name: Upload Artifact (macOS ARM)
        uses: actions/upload-artifact@v4
        with:
          name: FluxionViewer macOS ARM
          path: ./publish/osx-arm64/
